'''Product flags for icedrift'''
id_flags = {
    # Flag values for daily images (internal)
    'tcimage_outside_grid': -2,
    'tcimage_nodata': -1,
    'tcimage_ok': 0,
    'tcimage_unprocessed': 1,
    'tcimage_failed': 2,
    # Flag values for daily products (internal)
    'icedrift_unprocessed': -1,
    'icedrift_ok': 0,
    'icedrift_outside_imgborder': 1,
    'icedrift_closeto_imgborder': 2,
    'icedrift_center_over_land': 3,
    'icedrift_noice': 4,
    'icedrift_closeto_coast_or_edge': 5,
    'icedrift_closeto_missing': 6,
    'icedrift_closeto_unprocessed': 7,
    'icedrift_optimisation_fails': 8,
    'icedrift_fails': 9,
    'icedrift_lowcorrelation': 10,
    'icedrift_toolong': 11,
    'icedrift_refused_by_neighbours': 12,
    'icedrift_correct_by_neighbours': 13,
    'icedrift_noaverage': 14,
    'icedrift_summerhold': 15,
    'icedrift_oiinterp': 16,
    'icedrift_smaller_pattern': 17,
    'icedrift_masked_nwp': 18,
    'icedrift_windgapfill': 19,
    'icedrift_maxdriftmask': 20,
    'icedrift_fillbywind': 21,
    'icedrift_blendwithwind': 22,
    'icedrift_nbflags': 23,
    # Flag values for daily uncertainties (internal)
    'icedriftpost_unprocessed': -1,
    'icedriftpost_ok': 0,
    'icedriftpost_dif': 1,
    'icedriftpost_inv': 2,
    'icedriftpost_neg': 3,
    'icedriftpost_novector': -1,
}
